name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'  
    - name: Build the Docker image
      run: cd qi-frontend && yarn install && yarn build && cd .. && docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/qi:latest
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push
      run: docker push ${{ secrets.DOCKERHUB_USER }}/qi:latest
